[package]
name = "archivindex-serde"
description = "Serde helpers for borrowing string data from the deserializer input"
authors.workspace = true
repository.workspace = true
documentation = "https://docs.rs/crate/archivindex-serde/"
keywords = ["serde", "borrow", "zero-copy"]
categories = ["encoding"]
edition.workspace = true
rust-version.workspace = true
readme.workspace = true
license.workspace = true
version.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
serde.workspace = true

[dev-dependencies]
serde_json.workspace = true
